CREATE TABLE IF NOT EXISTS solar_proposals (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  average_rate_kwh DECIMAL(10, 2) NOT NULL,
  fixed_costs DECIMAL(10, 2) NOT NULL,
  escalation DECIMAL(5, 2) NOT NULL,
  monthly_bill DECIMAL(10, 2) NOT NULL,
  number_of_solar_panels INTEGER NOT NULL,
  yearly_energy_produced INTEGER NOT NULL,
  energy_offset INTEGER NOT NULL,
  solar_panel_design TEXT,
  battery_name VARCHAR(255) NOT NULL,
  inverter_name VARCHAR(255) NOT NULL,
  operating_mode VARCHAR(50) NOT NULL,
  capacity DECIMAL(10, 2) NOT NULL,
  output_kw DECIMAL(10, 2) NOT NULL,
  cost DECIMAL(10, 2) NOT NULL,
  backup_allocation VARCHAR(50) NOT NULL,
  battery_image TEXT,
  essentials_days DECIMAL(5, 2) NOT NULL,
  appliances_days DECIMAL(5, 2) NOT NULL,
  whole_home_days DECIMAL(5, 2) NOT NULL,
  payback_period DECIMAL(5, 2) NOT NULL,
  total_system_cost DECIMAL(10, 2) NOT NULL,
  lifetime_savings DECIMAL(10, 2) NOT NULL,
  net_cost DECIMAL(10, 2) NOT NULL,
  incentives DECIMAL(10, 2) NOT NULL,
  solar_system_model VARCHAR(255) NOT NULL,
  solar_system_quantity INTEGER NOT NULL,
  solar_system_price DECIMAL(10, 2) NOT NULL,
  storage_system_model VARCHAR(255) NOT NULL,
  storage_system_quantity INTEGER NOT NULL,
  storage_system_price DECIMAL(10, 2) NOT NULL
);

